sudo: true
language: python
dist: trusty
matrix:
  include:
    - env:
        - TOXENV=marionette
        - FOO=1
    - env:
        - TOXENV=marionette
        - FOO=2
    - env:
        - TOXENV=marionette
        - FOO=3
    - env:
        - TOXENV=marionette
        - FOO=4
before_install:
  - mkdir -p ~/drivers; export PATH=~/drivers:$PATH;
  - if [[ $TOXENV == marionette ]]; then
      DATA=$(curl -s --stderr stderr.out https://api.github.com/repos/mozilla/geckodriver/releases/latest);
      echo $?;
      echo $DATA;
      cat stderr.out;
      GECKODRIVER_VERSION=$(echo $DATA | python -c "import sys, json; sys.stdout.write(json.load(sys.stdin)['tag_name'])");
      GECKODRIVER_URL="https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz";
      FILE=`mktemp`; wget "$GECKODRIVER_URL" -qO $FILE && tar xz -C ~/drivers -f $FILE geckodriver; rm $FILE; chmod 777 ~/drivers/geckodriver;
      ~/drivers/geckodriver --version;
    fi
script: "true"
